### ISSUE TITLE
/ipns/ instead of /dns/

### ISSUE THREAD

**Issue by sixcorners** [ipfs/go-dnslink#8]
I think the examples in the README should be /ipns/ instead of /dns/.
Does /dns/ work? When I tried to test it I don't think it worked.

**Comment by Stebalien** [comment]
You're right. Mind filing a PR?

**Comment by sixcorners** [comment]
It looks like there is some stuff in dnslink.go mentioning /dns/. Should that be changed too?

**Comment by ghost** [comment]
I am not even sure the code in this repo is used anywhere.

> mentioning /dns/. Should that be changed too?

Yes `/dns` is definitely not a thing anymore
